# Generated by Django 5.2 on 2025-04-15 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Additive",
            fields=[
                ("id_additive", models.AutoField(primary_key=True, serialize=False)),
                ("additive_name", models.CharField(max_length=50)),
                ("additive_cost", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Broker",
            fields=[
                ("id_broker", models.AutoField(primary_key=True, serialize=False)),
                ("broker_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Commodity_Group",
            fields=[
                (
                    "id_commodity_group",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("commodity_group_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Commodity_Subtype",
            fields=[
                (
                    "id_commodity_subtype",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("commodity_subtype_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Commodity_Type",
            fields=[
                (
                    "id_commodity_type",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("commodity_type_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Cost_Center",
            fields=[
                ("id_cost_center", models.AutoField(primary_key=True, serialize=False)),
                ("cost_center_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Counterparty",
            fields=[
                (
                    "id_counterparty",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("counterparty_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Counterparty_Facility",
            fields=[
                (
                    "id_counterparty_facility",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("counterparty_facility_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                ("id_currency", models.AutoField(primary_key=True, serialize=False)),
                ("currency_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Delivery_Format",
            fields=[
                (
                    "id_delivery_format",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("delivery_format_name", models.CharField(max_length=50)),
                (
                    "delivery_format_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ICOTERM",
            fields=[
                ("id_icoterm", models.AutoField(primary_key=True, serialize=False)),
                ("icoterm_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Sociedad",
            fields=[
                ("id_sociedad", models.AutoField(primary_key=True, serialize=False)),
                ("sociedad_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="TableNames",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Trade_Operation_Type",
            fields=[
                (
                    "id_trade_operation_type",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("trade_operation_type_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Trader",
            fields=[
                ("id_trader", models.AutoField(primary_key=True, serialize=False)),
                ("trader_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Commodity",
            fields=[
                ("id_commodity", models.AutoField(primary_key=True, serialize=False)),
                ("commodity_name_short", models.CharField(max_length=50)),
                (
                    "commodity_group",
                    models.ForeignKey(
                        db_column="id_commodity_group",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nextcrm.commodity_group",
                    ),
                ),
                (
                    "commodity_subtype",
                    models.ForeignKey(
                        db_column="id_commodity_subtype",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nextcrm.commodity_subtype",
                    ),
                ),
                (
                    "commodity_type",
                    models.ForeignKey(
                        db_column="id_commodity_type",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nextcrm.commodity_type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("broker_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("entrega", models.CharField(max_length=50)),
                ("freight_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("forex", models.DecimalField(decimal_places=4, max_digits=10)),
                ("payment_days", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("delivery_period", models.DateField()),
                ("date", models.DateField()),
                (
                    "additive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nextcrm.additive",
                    ),
                ),
                (
                    "broker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nextcrm.broker"
                    ),
                ),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nextcrm.commodity",
                    ),
                ),
                (
                    "commodity_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nextcrm.commodity_group",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nextcrm.cost_center",
                    ),
                ),
                (
                    "counterparty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nextcrm.counterparty",
                    ),
                ),
                (
                    "broker_fee_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broker_fee_contracts",
                        to="nextcrm.currency",
                    ),
                ),
                (
                    "trade_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_contracts",
                        to="nextcrm.currency",
                    ),
                ),
                (
                    "delivery_format",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nextcrm.delivery_format",
                    ),
                ),
                (
                    "icoterm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nextcrm.icoterm",
                    ),
                ),
                (
                    "sociedad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nextcrm.sociedad",
                    ),
                ),
                (
                    "trade_operation_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nextcrm.trade_operation_type",
                    ),
                ),
                (
                    "trader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nextcrm.trader"
                    ),
                ),
            ],
        ),
    ]
